services:
  - type: web
    name: fastapi
    runtime: docker
    plan: free
    repo: https://github.com/Zurgambayev/nFactorial_2024
    region: frankfurt
    branch: main
    buildFilter:
      paths:
      - parser/**